[package]
name = "lix-engine"
version = "0.1.0"
edition = "2021"

[lib]
name = "lix_engine"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "lix-engine-router"
path = "src/main.rs"

[dependencies]
sqlparser = "0.53.0"
